### ISSUE TITLE
Default .env file that works for you

### ISSUE THREAD

**Issue by T0071** [alex43268/iptv-handler#1]
Hello @alex43268, I really enjoy this project, but am having trouble testing it out. Can you please supply your `.env` that works for you. I've tryed about everything I can think of and can't seem to get it working.

Current `.env` file:

```
DATABASE_URL="mysql://db:db@host.docker.internal:3306/iptvhandler"
M3U="https://iptv-org.github.io/iptv/categories/auto.m3u"
PROXY_DOMAIN="localhost:3000"
```

**Comment by alex43268** [comment]
Hi!

Glad you like the project.

I ran into an issue as well when running the app without RUST_LOG environment variable set. I have rectified that issue now. 

I also noticed that you're using a playlist with only HLS entries (.m3u8), there is no proxy support for HLS atm and it's yet to be implemented. 

The app should start fine now using your current .env file tough.
